### PR TITLE
fix: removing filter with more than one colon

### LINKED ISSUE #376: Bug: Removing filter starting with  config:cros//*
I can't seem to clear the `config:cros//*` configs by pressing the "X" close to their name. I'm able to clear out other options though (e.g. `configs:x86_64_defconfig` can be removed without problems)

PS: Check if it's a problem with the special characters

https://kernelci.slack.com/archives/C067UJC404A/p1728639801023089https://kernelci.slack.com/archives/C067UJC404A/p1728639801023089

### PR DESCRIPTION
**Pull request by anajalvarenga**
Correct the filtering by clearing the option with more than two colons by pressing the “X” next to the name.

- Closes #376 

## How to test

1. open the [dashboard](http://localhost:5173/tree/1d227fcc72223cbdd34d0ce13541cbaab5e0d72f?tableFilter={%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22}&origin=maestro&currentTreeDetailsTab=treeDetails.builds&diffFilter={%22configs%22%3A{%22cros%3A%2F%2Fchromeos-6.6%2Fx86_64%2Fchromeos-intel-pineview.flavour.config%22%3Atrue%2C%22cros%3A%2F%2Fchromeos-6.6%2Fx86_64%2Fchromeos-amd-stoneyridge.flavour.config%22%3Atrue%2C%22x86_64_defconfig%22%3Atrue}}&treeInfo={%22gitBranch%22%3A%22master%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Ftorvalds%2Flinux.git%22%2C%22treeName%22%3A%22mainline%22%2C%22commitName%22%3A%22v6.12-rc2-205-g1d227fcc7222%22%2C%22headCommitHash%22%3A%221d227fcc72223cbdd34d0ce13541cbaab5e0d72f%22})
2. Try to clear the "configs:cros://*" options

### CODE REVIEW

File: dashboard/src/pages/TreeDetails/TreeDetailsFilterList.tsx [hunk 1]
```diff
@@ -32,7 +32,8 @@ const TreeDetailsFilterList = ({
 
   const onClickItem = useCallback(
     (flatValue: string, _: number) => {
-      const [field, value] = flatValue.split(':');
+      const [field, ...rest] = flatValue.split(':');
+      const value = rest.join(':');
```
Comment (WilsonNet) [inline dashboard/src/pages/TreeDetails/TreeDetailsFilterList.tsx:36]: `split` has another argument called limit which can make split less greedy, so you don't need to rejoin again

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split

Comment (Francisco2002) [reply dashboard/src/pages/TreeDetails/TreeDetailsFilterList.tsx:36]: wow, nice tip!!!!

Comment (anajalvarenga) [reply dashboard/src/pages/TreeDetails/TreeDetailsFilterList.tsx:36]: If I use `limit`, I still get the same error because your functionality is to "stops when limit entries have been placed in the array". So the return of `"configs:cros://chromeos-6.6/x86_64/chromeos-intel-pineview.flavour.config
".split(":", 2)` would be `["configs", "cros"]`

**Review by MarceloRobert — APPROVED** [review]
Looks good to me

**Review by Francisco2002 — APPROVED** [review]
