### PR TITLE
fix(#20): set the start index correctly when some filter is applied

### LINKED ISSUE #20: [Bug] [Builds Tab] Itens navigation breaks after filters change

### PR DESCRIPTION
**Pull request by mari1912**
- closes #20

### CODE REVIEW

File: dashboard/src/hooks/usePagination.tsx [hunk 1]
```diff
@@ -13,6 +13,7 @@ export const usePagination = (
   const [endIndex, setEndIndex] = useState(0);
 
   useEffect(() => {
+    setStartIndex(0); //restart the index whenever there is a change in filters
```
Comment (WilsonNet) [inline dashboard/src/hooks/usePagination.tsx:16]: this won't work if the itemsPorPage and totalItems have the same count, needs to add `diffFilter` and `filter` to the dependency array

Comment (WilsonNet) [reply dashboard/src/hooks/usePagination.tsx:16]: you will need `useSearch` for this one

Comment (mari1912) [reply dashboard/src/hooks/usePagination.tsx:16]: Can you give me an example when it's possible? I tried with http://localhost:5173/tree/0bdf955f408e17b64d9dc4de09d3a2fc4f233aca?tableFilter=all&currentTreeDetailsTab=treeDetails.builds&diffFilter=%7B%7D changing the itemsPerPage and it doesn't seem to be broken

Comment (WilsonNet) [reply dashboard/src/hooks/usePagination.tsx:16]: it will be a rare case if not never, but it is possible since are primitives in javascript and the `useEffect` wont detect a change if they are the same but coming from another source

**Review by WilsonNet — APPROVED** [review]
it's also missing `tableFilter` which  also changes the table

**Comment by WilsonNet** [comment]
I just realized that there is a regression and tableFilter is not being used anymore when changing the tabel filter
