### PR TITLE
fix: update new issue icon

### LINKED ISSUE #941: Update new label indication. Use a small circle dot

### PR DESCRIPTION
**Pull request by murilx**
Closes #941 

Based on this generated code: https://css-generators.com/starburst-shape/

**Important:** This solution uses [clip-path](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path) if there's any need to support older browsers, than the implementation might need to change

## Visual Reference
image

### CODE REVIEW

File: dashboard/src/components/Cards/IssuesList.tsx [hunk 1]
```diff
@@ -132,9 +132,7 @@ const IssuesList = ({
           tagPills?.unshift(
             <Tooltip>
               <TooltipTrigger className="cursor-default">
-                <Badge variant="greenTag">
-                  {formatMessage({ id: 'global.new' })}
-                </Badge>
+                <div className="starburst bg-red aspect-square w-[20px]"></div>
```
Comment (MarceloRobert) [inline dashboard/src/components/Cards/IssuesList.tsx:135]: nit to make it even more visible
```suggestion
                <div className="starburst bg-red aspect-square w-[24px]"></div>
```

**Review by MarceloRobert — APPROVED** [review]
LGTM

File: dashboard/src/index.css [hunk 2]
```diff
@@ -4,6 +4,19 @@
 
 @custom-variant dark (&:is(.dark *));
 
+@layer utilities {
```
Comment (WilsonNet) [inline dashboard/src/index.css:7]:
```suggestion
@layer components {
```
this is not an utility

**Review by WilsonNet — APPROVED** [review]
looks good, a minor fix, pre approving
