### PR TITLE
fix: disable highlight on log viewer by file size

### LINKED ISSUE #1059: Disable syntax highlight in log excerpt based on file size
It is getting pretty slow in large files

### PR DESCRIPTION
**Pull request by murilx**
I couldn't find a log greater then 4 million characters. I also did some testing but to be sure I decided to go for this constraint of 6 million characters.

Closes #1059

## How to test
- Open logs in redhat origin and verify that every log does not take to much time to load and, in some cases, highlighted
[(localhost) example of a log with 14 million characters](http://localhost:5173/log-viewer?itemId=redhat%3A1729170198-x86_64-kernel-automotive&o=redhat&type=build&url=https%3A%2F%2Fs3.amazonaws.com%2Farr-cki-prod-trusted-artifacts%2Ftrusted-artifacts%2F1729170198%2Fbuild_x86_64%2F9489093468%2Fartifacts%2Fbuild.log)

### CODE REVIEW

File: dashboard/src/locales/messages/index.ts [hunk 1]
```diff
@@ -220,6 +220,8 @@ export const messages = {
       'This log url is not supported in the log viewer yet, but you can still download the log in the link above',
     'logSheet.noLogFound': 'No logs available',
     'logSheet.title': 'Log Viewer',
+    'logViewer.disabledHighlight':
+      'The highlight is disabled in this log due to of log size',
```
Comment (MarceloRobert) [inline dashboard/src/locales/messages/index.ts:224]:
```suggestion
      'The text highlight was disabled in this log due to log size',
```

**Review by MarceloRobert — APPROVED** [review]
LGTM, just an improvement in the message
