### PR TITLE
fix: wrong usage of misc platform field

### LINKED ISSUE #261: Add platform data to Test Details Page (from misc field, works only for maestro)

### PR DESCRIPTION
**Pull request by lfjnascimento**
- misc fields are json strings and must be parsed before being used as an object

| Before | After |
|--------|--------|
| image | image |

Close #261

### CODE REVIEW

File: dashboard/src/pages/TestDetails/TestDetails.tsx [hunk 1]
```diff
@@ -53,6 +53,11 @@ const LogExcerpt = ({ test }: TTestDetailsDefaultProps): JSX.Element => {
 
 const TestDetailsSection = ({ test }: { test: TTestDetails }): JSX.Element => {
   const intl = useIntl();
+  const misc = test.environment_misc ?? test.misc;
+  const platform: string = misc
+    ? JSON.parse(misc).platform
```
Comment (lfjnascimento) [inline dashboard/src/pages/TestDetails/TestDetails.tsx:58]: would be better to move the parsing to the data fetch function

**Review by WilsonNet — APPROVED** [review]
nice
