### PR TITLE
Fix Filter in History Charts

### LINKED ISSUE #264: Selected filters do not affect History Chart but they should

### PR DESCRIPTION
**Pull request by Francisco2002**
Change the Tree Commit History SQL to allow pass filters in history charts.

**How to test**
1. Select a tree of your choice.
2. Play with filters and see the changes in History Chart

Screenshot from 2024-10-24 12-22-28

Close #264

### CODE REVIEW

File: dashboard/src/api/TreeDetails.tsx [hunk 1]
```diff
@@ -244,15 +244,18 @@ const fetchTreeCommitHistory = async (
   origin: string,
   gitUrl: string,
   gitBranch: string,
+  filters: TTreeDetailsFilter,
 ): Promise<TTreeCommitHistoryResponse> => {
+  const searchParam = mapFiltersToUrlSearchParams(filters);
```
Comment (WilsonNet) [inline dashboard/src/api/TreeDetails.tsx:249]: in the future we should remove this `mapFiltersToUrlSearchParams` so can you add a TODO to not use this? Axios can handle the serialization

Comment (WilsonNet) [inline dashboard/src/api/TreeDetails.tsx:249]: also, can you add a `TSDOC`  `/** @deprecated */` to the function so we stop the bleeding

File: backend/kernelCI_app/views/treeCommitsHistory.py [hunk 2]
```diff
@@ -1,13 +1,110 @@
...
+                'filters': []
+            },
+            'test': {
+                'table_alias': 't',
+                'filters': []
+            }
+        }
+        self.field_values = dict()
+
+    def get_filters(self, filter_params):
```
Comment (WilsonNet) [inline backend/kernelCI_app/views/treeCommitsHistory.py:33]: nit: can you rename to `__get_filters` to show that is a private function

File: backend/kernelCI_app/views/treeCommitsHistory.py [hunk 3]
```diff
@@ -1,13 +1,110 @@
...
+        for f in filter_params.filters:
```
Comment (WilsonNet) [inline backend/kernelCI_app/views/treeCommitsHistory.py:34]: this logic seems very similar to the one that is being used already, can you add a TODO to unite the filters logic:?

File: backend/kernelCI_app/views/treeCommitsHistory.py [hunk 4]
```diff
@@ -73,55 +184,67 @@ def get(self, request, commit_hash):
...
+                SUM(CASE WHEN t.status = 'SKIP' AND t.path LIKE 'boot%%' THEN 1 ELSE 0 END)
+                AS boots_skip_count
+            FROM
+                relevant_checkouts AS c
+            INNER JOIN
+                builds AS b
+                ON
+                c.id = b.checkout_id
+            LEFT JOIN
+                tests AS t
```
Comment (WilsonNet) [inline backend/kernelCI_app/views/treeCommitsHistory.py:213]: this query can gets very heavy after they turn back the notifications in the backend, I think would be smart to create a CTE with tests so that join is made only a single time

**Review by WilsonNet — APPROVED** [review]
worked great on my tests

**Review by MarceloRobert — APPROVED** [review]
Looks good to me, the graph animates nicely too
