### PR TITLE
Fix: hardware commit selector

### LINKED ISSUE #783: Bug(Hardware details): when switching commit history in select menu, it goes back right after it changes
If you got to any hardware details, and change the value of a commit.

It change the results, but short after go back to the original state

### PR DESCRIPTION
**Pull request by murilx**
Added a new state `treeIndexesLength` that keep track of the size of number of trees there are in the header table. This was necessary because the backend expects a object that maps each tree index to its respective selected commit, but it couldn't correctly get all the tree indexes from the query parameter since it defaults to an empty array when all trees are selected. This state is then used when the query param is an empty array to create this object
    
Closes #783 

## How to test
This hardware is a good one for testing: [google,kingoftown](http://localhost:5173/hardware/google%2Ckingoftown?et=1738087200&st=1737655200), specially the `mainline/master` branch that has a lot of commits and different values between them. 
- Try to change the commits and see if the status in the header table change accordingly, also check for the data in the tabs. 
- Try to select or deselect trees from the header table and check if the data from the tabs are updated correctly. Also try to do it with changed commits in other trees to see if they don't update alone when selecting or deselecting trees.

### CODE REVIEW

File: dashboard/src/pages/hardwareDetails/HardwareDetailsHeaderTable.tsx [hunk 1]
```diff
@@ -142,7 +142,11 @@ const CommitSelector = ({
 
   return (
     <div className="flex items-center gap-4">
-      <Select onValueChange={navigateToThePast} disabled={isMainPageLoading}>
+      <Select
+        onValueChange={navigateToThePast}
+        value={treeCommits[treeIndex] ?? headCommitHash}
```
Comment (Francisco2002) [inline dashboard/src/pages/hardwareDetails/HardwareDetailsHeaderTable.tsx:152]: nit: use `commitHash` defined in line 140

File: dashboard/src/api/hardwareDetails.ts [hunk 2]
```diff
@@ -24,12 +24,19 @@ const TREE_SELECT_HEAD_VALUE = 'head';
...
 ): Record<string, string> => {
   const selectedTrees: Record<string, string> = {};
 
-  selectedIndexes.forEach(idx => {
-    const key = idx.toString();
+  const selectedArray = treeIndexesLength
+    ? selectedIndexes.length === 0
+      ? Array.from({ length: treeIndexesLength }, (_, i) => i)
+      : selectedIndexes
+    : selectedIndexes;
```
Comment (Francisco2002) [inline dashboard/src/api/hardwareDetails.ts:36]:
```suggestion
  const selectedArray = treeIndexesLength && selectedIndexes.length === 0
      ? Array.from({ length: treeIndexesLength }, (_, i) => i)
      : selectedIndexes;
```

File: dashboard/src/pages/hardwareDetails/HardwareDetails.tsx [hunk 3]
```diff
@@ -137,6 +137,7 @@ function HardwareDetails(): JSX.Element {
     });
   }, [navigate]);
 
+  const [treeIndexesLength, setTreeIndexesLength] = useState(0);
```
Comment (Francisco2002) [inline dashboard/src/pages/hardwareDetails/HardwareDetails.tsx:140]: This props don't need to update the component when it changes, because he is a dependency of `useQuery`. So, you could use `useRef` here and reduce the re-renders.

**Comment by MarceloRobert** [comment]
IMO you shouldn't send the selected tree list to the backend when all of the trees are selected and all of them are in the head commit hash, meaning that you should only send it if any tree was unselected _or_ any of them had the commit hash changed

File: dashboard/src/pages/hardwareDetails/HardwareDetails.tsx (hunk 3 above)
Comment (murilx) [reply dashboard/src/pages/hardwareDetails/HardwareDetails.tsx:140]: Might still need to use `useState` in this case since `treeIndexesLength` is being read by `useHardwareDetailsLazyLoaded` and AFAIK this happens during the component rendering and refs shouldn't be read during rendering.

File: dashboard/src/pages/hardwareDetails/HardwareDetailsHeaderTable.tsx [hunk 4]
```diff
@@ -366,6 +386,8 @@ export function HardwareHeader({
     );
   }, [selectedIndexes, treeItems.length]);
 
+  const columns = getColumns(setTreeIndexesLength);
```
Comment (MarceloRobert) [inline dashboard/src/pages/hardwareDetails/HardwareDetailsHeaderTable.tsx:389]: `useMemo` here

**Review by MarceloRobert — COMMENTED** [review]
Seems to be working on my tests now

File: dashboard/src/utils/utils.ts [hunk 5]
```diff
@@ -199,3 +199,10 @@ export const isStringRecord = (
     !Array.isArray(obj)
   );
 };
+
+export const isEmptyObject = (obj: Record<string, unknown>): boolean => {
+  for (const prop in obj) {
+    if (Object.prototype.hasOwnProperty.call(obj, prop)) return false;
+  }
+  return true;
+};
```
Comment (Francisco2002) [inline dashboard/src/utils/utils.ts:208]: you can do `Object.keys(obj).length == 0` to test if a object is empty

**Review by Francisco2002 — APPROVED** [review]
approved with a comment

File: dashboard/src/utils/utils.ts (hunk 5 above)
Comment (murilx) [reply dashboard/src/utils/utils.ts:208]: Although in the worst case scenario both of these solutions are `O(n)`, in the average scenario this function would work much faster. In the situation it's being used I'd say it would finish in the first iteration most of the time. Now, the truth is that `treeCommits` is a very little object, in the worst case it would have something like a hundred elements so it's probably not something to care about now
