### PR TITLE
Fix/top bar

### LINKED ISSUE #26: [Bug] Trees Listing Page: Title and trees list should be aligned

### LINKED ISSUE #109: [Bug] Search bar missing

### PR DESCRIPTION
**Pull request by mari1912**
- closes #26 
- closes #109

### CODE REVIEW

File: dashboard/src/pages/Trees.tsx [hunk 1]
```diff
@@ -14,20 +16,22 @@ const Trees = (): JSX.Element => {
...
   return (
     <>
       <div className="w-full bg-lightGray px-16 pt-24">
         <TreeListingPage inputFilter={inputSearchText} />
       </div>
-      <div className="fixed top-0 mx-52 flex w-full pl-6 pr-12 pt-5">
+      <div className="fixed top-0 z-10 mx-52 flex w-full pl-6 pr-12 pt-5">
         <div className="flex w-2/3 items-center px-6">
           {/* placeholder for search */}
           {/* TODO: use i18n for the input placeholder */}
```
Comment (lfjnascimento) [inline dashboard/src/pages/Trees.tsx:29]: remove TODO

File: dashboard/src/components/TreeListingPage/TreeListingPage.tsx [hunk 2]
```diff
@@ -38,7 +38,11 @@ const TreeListingPage = ({ inputFilter }: ITreeListingPage): JSX.Element => {
       return [];
     } else {
       return data
-        .filter(tree => tree.git_commit_hash?.includes(inputFilter))
+        .filter(
+          tree =>
+            tree.git_commit_hash?.includes(inputFilter) ||
+            tree.tree_names.includes(inputFilter),
```
Comment (lfjnascimento) [inline dashboard/src/components/TreeListingPage/TreeListingPage.tsx:44]: partial searching by tree name is not working because tree_names is a array here

**Review by lfjnascimento — APPROVED** [review]
