### PR TITLE
fix: show 'NULL' instead of nothing in status col

### LINKED ISSUE #714: fix: show NULL in status column instead of showing nothing
Something that happens [here (localhost)](http://localhost:5173/hardware/amlogic%2Ca311d?currentPageTab=global.boots&endTimestampInSeconds=1734978600&startTimestampInSeconds=1734546600&tableFilter%7CbootsTable=inconclusive&tableFilter%7CbuildsTable=all&tableFilter%7CtestsTable=all) for example.

## Visual reference
boots table

### PR DESCRIPTION
**Pull request by murilx**
After further research, apparently the problem only existed in the boots table in hardware details. The can be seem in this page [Tests table showing 'NULL' status correctly](https://staging.dashboard.kernelci.org:9000/tree/0d7aea765c41401c36c9d0a1d039a2cf30df430e?currentPageTab=global.tests&treeInfo%7CcommitName=v6.13-rc3-4-g0d7aea765c41&treeInfo%7CgitBranch=for-kernelci&treeInfo%7CgitUrl=https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Fardb%2Flinux.git&treeInfo%7CheadCommitHash=0d7aea765c41401c36c9d0a1d039a2cf30df430e&treeInfo%7CtreeName=ardb), this page [Boots table showing 'NULL' status correctly](https://staging.dashboard.kernelci.org:9000/tree/e43857dccff0b7f2e13a9edf394f1283c116a4df?currentPageTab=global.boots&tableFilter%7CbootsTable=inconclusive&tableFilter%7CbuildsTable=all&tableFilter%7CtestsTable=all&treeInfo%7CcommitName=v6.13-rc1-52-ge43857dccff0&treeInfo%7CgitBranch=for-next&treeInfo%7CgitUrl=https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Fqcom%2Flinux.git&treeInfo%7CheadCommitHash=e43857dccff0b7f2e13a9edf394f1283c116a4df&treeInfo%7CtreeName=qcom) in the build table code in `src/components/BuildsTable/DefaultBuildsColumn.tsx` (since I couldn't find a tree or hardware that had Build with null status)

```js
    cell: ({ row }): string => {
      return row.getValue('status')
        ? row.getValue('status')!.toString().toUpperCase()
        : 'NULL';
    },
```

Here an example of the bug happening in the boots table for hardware details
- [Boots table in staging showing nothing](https://staging.dashboard.kernelci.org:9000/hardware/amlogic%2Ca311d?currentPageTab=global.boots&endTimestampInSeconds=1734982200&startTimestampInSeconds=1734550200&tableFilter%7CbootsTable=inconclusive&tableFilter%7CbuildsTable=all&tableFilter%7CtestsTable=all)
- [Boots table in localhost showing NULL](http://localhost:5173/hardware/amlogic%2Ca311d?currentPageTab=global.boots&endTimestampInSeconds=1734978600&startTimestampInSeconds=1734546600&tableFilter%7CbootsTable=inconclusive&tableFilter%7CbuildsTable=all&tableFilter%7CtestsTable=all)

This happens because in the TreeDetailsView there's already a process ensuring that `record["test_status"] = "NULL"` if status is null/None in the database, and HardwareDetailsView does not have the same processing being done.

Closes #714 

## Visual reference
Before
image

After
image

### CODE REVIEW

File: dashboard/src/components/BootsTable/BootsTable.tsx [hunk 1]
```diff
@@ -131,7 +131,7 @@ export function BootsTable({
           id: e.id,
           path: e.path,
           startTime: e.startTime,
-          status: e.status,
+          status: e.status ?? 'NULL',
```
Comment (WilsonNet) [inline dashboard/src/components/BootsTable/BootsTable.tsx:134]: put it on a constant

File: dashboard/src/components/TestsTable/TestsTable.tsx [hunk 2]
```diff
@@ -103,7 +103,7 @@ export function TestsTable({
         duration: e.duration?.toString() ?? '',
         path: e.path,
         start_time: e.startTime,
-        status: e.status,
+        status: e.status ?? 'NULL',
```
Comment (WilsonNet) [inline dashboard/src/components/TestsTable/TestsTable.tsx:106]: ditto about constant

**Review by WilsonNet — APPROVED** [review]
worked on my tests, just a minor comment

**Review by Francisco2002 — APPROVED** [review]
Nice job!!
