### PR TITLE
Fix: Update Icons and Log Visibility

### LINKED ISSUE #806: Make view log inside details VERY visible

### PR DESCRIPTION
**Pull request by murilx**
- Remove icons from fields that aren't clickable
- Change logs icon to a different one, made it larger and added a tooltip to the icon
- Added underline and hover text colors to all clickable fields

Closes #806

## Visual reference
Before
image

After
image

### CODE REVIEW

File: dashboard/src/components/BuildDetails/BuildDetails.tsx [hunk 1]
```diff
@@ -169,10 +160,11 @@ const BuildDetails = ({
               },
               {
                 title: 'global.status',
+                linkText: data.valid ? 'VALID' : 'INVALID',
```
Comment (MarceloRobert) [inline dashboard/src/components/BuildDetails/BuildDetails.tsx:163]: builds can also be inconclusive, with a NULL valid status

File: dashboard/src/components/Icons/LogView.tsx
Comment (MarceloRobert) [inline dashboard/src/components/Icons/LogView.tsx:1]: Also add this to the LogViewerCard component

File: dashboard/src/components/LinkWithIcon/LinkWithIcon.tsx [hunk 2]
```diff
@@ -36,7 +36,7 @@ const LinkWithIcon = ({
       {linkComponent ?? (
         <WrapperLink
           className={cn('flex flex-row items-center gap-1', {
-            'hover:text-gray-900': onClick,
+            'underline hover:text-gray-900': onClick || link,
```
Comment (Francisco2002) [inline dashboard/src/components/LinkWithIcon/LinkWithIcon.tsx:39]: This is amazing!!!
Nice finding

**Review by Francisco2002 — APPROVED** [review]
Nice job!!

File: dashboard/src/components/BuildDetails/BuildDetails.tsx [hunk 3]
```diff
@@ -169,10 +160,15 @@ const BuildDetails = ({
               },
               {
                 title: 'global.status',
+                linkText: data.valid
+                  ? 'VALID'
+                  : data.valid !== null
+                    ? 'INVALID'
+                    : 'UNKNOWN',
```
Comment (MarceloRobert) [inline dashboard/src/components/BuildDetails/BuildDetails.tsx:167]: in the table, a null build valid is just represented as "NULL" or you could use the `UNKNOWN_STRING` const

**Review by MarceloRobert — APPROVED** [review]
Just one string change, pre-approving

File: dashboard/src/components/BuildDetails/BuildDetails.tsx (hunk 3 above)
Comment (murilx) [reply dashboard/src/components/BuildDetails/BuildDetails.tsx:167]: Might stick to what is defined in the table
