### PR TITLE
fix(breadcrumbs): adjust LogViewer, Build Details and Test Details breadcrumb for new URL structure

### LINKED ISSUE #1314: bug: treeDetails breadcrumb breaks on new url
1. Arrive at a tree details with the direct url (such as https://staging.dashboard.kernelci.org:9000/build/maestro%3A6859c9155c2cf25042d4f48c)
2. Go to a build, test or issue details
3. Click on the "tree details" in the breadcrumb

Currently, it tries to go to the long url treeDetails, but without the treeInfo in the url the page breaks.

The expected behavior is to go back to the treeDetails page that it was, be it with long or direct url.

### PR DESCRIPTION
**Pull request by danieldiasbarbo**
## Description
This PR fixes the breadcrumb links for the BuildDetails, TestDetails and LogViewer pages to accommodate the updated URL structure.
Previously, breadcrumbs were not resolving correctly due to changes in the route parameters.
With this fix, the breadcrumb now accurately reflects the current path

## Changes
- [x] Remanaged the routerState in pages like LogViewer, BuildDetails, and TestDetails
- [x] Updated breadcrumb logic to consistently resolve to the correct TreeDetails url

## How to test
1. Navigate to a TreeDetails page via TreeListing or directly via URL
1. From there, open related pages such as LogViewer, BuildDetails and TestDetails
1. Verify that the breadcrumb displays correctly in each case and accurately reflects the full path back to the TreeDetails
1. Ensure no breadcrumb segment is broken or missing

Closes #1314

### CODE REVIEW

File: dashboard/src/components/Breadcrumb/TreeBreadcrumb.tsx [hunk 1]
```diff
@@ -22,7 +22,12 @@ const TreeBreadcrumb = ({
   searchParams: LinkProps['search'];
   locationMessage: MessageDescriptor['id'];
 }): JSX.Element => {
-  const treeId = useRouterState({ select: s => s.location.state.id });
+  const historyState = useRouterState({
+    select: s => s.location.state,
+  });
+  const { treeName, branch, id } = historyState;
+  const treeId = id;
```
[the remark this answers is not in the document]
Comment (danieldiasbarbo) [reply dashboard/src/components/Breadcrumb/TreeBreadcrumb.tsx]: Done.

File: dashboard/src/pages/LogViewer.tsx [hunk 2]
```diff
@@ -61,6 +61,9 @@ export function LogViewer(): JSX.Element {
   const { data, status } = useLogViewer(url);
   const { data: logData, isLoading } = useLogData(itemId ?? '', type);
 
+  const { treeName, branch, id } = historyState;
+  const canGoDirect = treeName && branch && id;
```
[the remark this answers is not in the document]
Comment (danieldiasbarbo) [reply dashboard/src/pages/LogViewer.tsx:65]: Done.

File: dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx [hunk 3]
```diff
@@ -25,6 +30,21 @@ export function TreeDetailsBuildsTable({
   const params = useParams({ from: urlFrom });
   const { tableFilter } = useSearch({ from: urlFrom });
   const navigate = useNavigate({ from: treeDetailsFromMap[urlFrom] });
+  const historyState = useRouterState({ select: s => s.location.state });
+
+  const { treeName, branch, id } = historyState;
```
[the remark this answers is not in the document]
Comment (giubrocchi) [reply dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx:35]: Yes, jest to keep the pattern between the files

File: dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx [hunk 4]
```diff
@@ -26,6 +31,22 @@ export function TreeDetailsBuildsTable({
...
+  const paramsHash = getStringParam(params, 'hash');
+
+  const stateIsSetted = treeName && branch && id;
+  const stateParams = useCallback(
+    () =>
+      !stateIsSetted
+        ? { treeName: paramsTreeName, branch: paramsBranch, id: paramsHash }
+        : {},
+    [stateIsSetted, paramsTreeName, paramsBranch, paramsHash],
+  )();
```
Comment (MarceloRobert) [inline dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx:48]: You are creating a callback function and calling it right away, why not use a `useMemo`?

File: dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx
Comment (MarceloRobert) [inline dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx:1]: You are checking the state only for the builds table, but it is possible to arrive at the treeDetails from any tab, since the tab state is stored in the url as well (like the `?p=t` in https://dashboard.kernelci.org/tree/android/android-mainline/03be386dfbc7e1c09d20dc1df62a245c49ae29a3?p=t)

Comment (MarceloRobert) [reply dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx:1]: Also, if you have the state set, you don't need to go to `/tree/$treeId/build/$buildId`, go directly to `/build/$buildId` and you avoid a redirect

File: dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx
Comment (MarceloRobert) [inline dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx:1]: ditto check state and go directly to `/test/$testId`

File: dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx
Comment (MarceloRobert) [inline dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx:1]: ditto check state and go directly to `/test/$testId`

**Review by MarceloRobert — COMMENTED** [review]
Mostly working, but needs improvement

File: dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx
Comment (danieldiasbarbo) [reply dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx:1]: I think i've resolved it. Needed to add the from in the state. Tested here and seems to be working if the state ends up not being setted in the TreeListing page.

File: dashboard/src/components/Breadcrumb/TreeBreadcrumb.tsx [hunk 5]
```diff
@@ -33,8 +38,12 @@ const TreeBreadcrumb = ({
         </BreadcrumbItem>
         <BreadcrumbSeparator />
         <BreadcrumbLink
-          to={`/tree/$treeId`}
-          params={{ treeId: treeId }}
+          to={canGoDirect ? '/tree/$treeName/$branch/$hash' : '/tree/$treeId'}
```
[the remark this answers is not in the document]
Comment (danieldiasbarbo) [reply dashboard/src/components/Breadcrumb/TreeBreadcrumb.tsx]: Pinged you on Slack. I have some questions on int.

File: dashboard/src/components/Breadcrumb/TreeBreadcrumb.tsx [hunk 6]
```diff
@@ -22,7 +22,43 @@ const TreeBreadcrumb = ({
   searchParams: LinkProps['search'];
   locationMessage: MessageDescriptor['id'];
 }): JSX.Element => {
-  const treeId = useRouterState({ select: s => s.location.state.id });
+  const historyState = useRouterState({
+    select: s => s.location.state,
+  });
+
+  const { treeName, branch, id: treeId } = historyState;
```
Comment (giubrocchi) [inline dashboard/src/components/Breadcrumb/TreeBreadcrumb.tsx:29]: nit: can destruct like the other files:

```
const { treeName, branch, id: treeId } = useRouterState({
    select: s => s.location.state,
  });
```

File: dashboard/src/components/Breadcrumb/TreeBreadcrumb.tsx [hunk 7]
```diff
@@ -22,7 +22,43 @@ const TreeBreadcrumb = ({
...
+  } = useMemo(
+    () =>
+      canGoDirect
+        ? {
+            to: '/tree/$treeName/$branch/$hash',
+            params: { treeName: treeName, branch: branch, hash: treeId },
+          }
+        : { to: '/tree/$treeId', params: { treeId: treeId } },
+    [canGoDirect, treeName, branch, treeId],
+  );
```
Comment (giubrocchi) [inline dashboard/src/components/Breadcrumb/TreeBreadcrumb.tsx:46]: You don't need to type the `treeParams` if you add `as const` to the objects

```suggestion
  const treeParams = useMemo(
    () =>
      canGoDirect
        ? {
            to: '/tree/$treeName/$branch/$hash',
            params: { treeName: treeName, branch: branch, hash: treeId },
          } as const
        : { to: '/tree/$treeId', params: { treeId: treeId } } as const,
    [canGoDirect, treeName, branch, treeId],
  );
```

File: dashboard/src/components/Breadcrumb/TreeBreadcrumb.tsx (hunk 6 above)
Comment (danieldiasbarbo) [reply dashboard/src/components/Breadcrumb/TreeBreadcrumb.tsx:29]: Good catch. Resolved

**Review by giubrocchi — APPROVED** [review]

**Review by MarceloRobert — APPROVED** [review]
All working on my tests, LGTM
