### PR TITLE
fix: feedback URL serialization handling in SendFeedback component

### LINKED ISSUE #1848: Malformed serialization for argument in the feedback URLs: `[object Object]`
Reported in the mailing list:

> URL used to send feedback:
> https://dashboard.kernelci.org/hardware[object Object] 

Easy to reproduce:

1. Open the dashboard
2. Click on "Send us feedback" in the sidebar
3. Click on either Github or Email and it will try to report a feedback like

```
https://github.com/kernelci/dashboard/issues/new?labels=feedback&title=[Feedback]:&body=%23%20Feedback%20Description%3A%0A%20%20%0A%23%23%20URL%20used%20to%20send%20feedback%3A%0Ahttps%3A%2F%2Fdashboard.kernelci.org%2Ftree%5Bobject%20Object%5D
```

```
href="mailto:kernelci-webdashboard@groups.io?body=Feedback%20Description%3A%0A%20%20%0AURL%20used%20to%20send%20feedback%3A%0Ahttps%3A%2F%2Fdashboard.kernelci.org%2Ftree%5Bobject%20Object%5D&subject=Dashboard Feedback"
```

### PR DESCRIPTION
**Pull request by gustavobtflores**
## Description

Fix feedback URL construction in the side menu so the generated GitHub issue body and email body include the correct current page URL.

## Changes

- Build `fullLocation` from `useLocation().href` and prepend `window.location.origin` when needed
- URL-encode the email subject

## How to test (if needed)

1. Start the dashboard and navigate to any page
2. Open the side menu and click "Send feedback"
3. Verify the GitHub and Email actions include the current URL correctly

Closes #1848

### CODE REVIEW

File: dashboard/src/components/SideMenu/SendFeedback.tsx [hunk 1]
```diff
@@ -25,27 +25,27 @@ const SendFeedback = (
...
-  const [fullLocation, setFullLocation] = useState(
-    `${window.location.origin}${location.pathname}${location.search}${location.hash}`,
-  );
-
-  useEffect(() => {
-    const newUrl = `${window.location.origin}${location.pathname}${location.search}${location.hash}`;
-    setFullLocation(newUrl);
+  const fullLocation = useMemo(() => {
+    const href = location.href;
+    // href is relative (starts with "/"), prepend origin
```
Comment (MarceloRobert) [inline dashboard/src/components/SideMenu/SendFeedback.tsx:30]: I thought that origin was like "maestro" or "linaro", but I see that it's localhost or staging or production. Maybe worth a comment in the code

**Review by MarceloRobert — APPROVED** [review]
LGTM, I tested and it seems fixed

**Review by alanpeixinho — APPROVED** [review]
Everything seems ok
